### ISSUE TITLE
[BUG] TypeError: Cannot read property 'addPopoverButton'

### ISSUE THREAD

**Issue by cibere** [qwerty-mods/copy-raw#2]
Hey, I was trying to use this plugin a while ago, but never got it to work. But, while looking into an issue with another plugin I started to see this in my console 

![SS of console](https://i.cibere.dev/Xe7ukq.png)

**Comment by Naim2000** [comment]
Since I never expected the option to be here, I may be wrong, but try make sure Replugged is up to date. I updated to 4.1.0 just now and the button is here
![image](https://user-images.githubusercontent.com/44107089/224556676-e878002f-b6e1-486e-9042-d8657e96e105.png)

**Comment by cibere** [comment]
Huh, updating to 4.1.0 fixed it
